replicaCount: 1
autoscaling:
  enabled: false
podDisruptionBudget:
  enabled: false
resources:
  requests:
    cpu: 100m
    memory: 256Mi
ingress:
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
  hosts:
    - host: agentgateway.dev.internal
      paths:
        - path: /
          pathType: Prefix
