replicaCount: 1
leaderElection:
  enabled: false
config:
  environment: dev
reconcilers:
  budget:
    requeueInterval: 5m # faster reconciliation in dev for tighter feedback loop
resources:
  requests:
    cpu: 100m
    memory: 128Mi
