{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels: {{- include "operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      name: metrics
      protocol: TCP
  selector: {{- include "operator.selectorLabels" . | nindent 4 }}
{{- end }}
