apiVersion: v1
kind: Secret
metadata:
  name: in-cluster-production
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    eks-agent-platform/enabled: "true"
    cluster_name: eks-production
    region: us-west-2
    environment: production
type: Opaque
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
