controller:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
ui:
  enabled: true
  ingress:
    enabled: true
    className: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
      - host: kagent.dev.internal
