# GENERATED by scripts/gen-lambda-pricing.mjs from
# packages/pricing/src/data/bedrock-pricing.json — DO NOT EDIT.
#
# Bedrock on-demand prices, USD per 1,000,000 tokens. This table is the Python
# projection of the pricing SSOT the TypeScript @eks-agent/pricing package
# imports; a CI drift gate (`node scripts/gen-lambda-pricing.mjs --check`)
# fails the build if the two diverge. To change a price, edit the JSON and
# regenerate — never hand-edit this file.

PRICING: dict[str, dict[str, float]] = {
    "amazon.nova-lite-v1:0": {"input": 0.0375, "output": 0.13},
    "amazon.nova-micro-v1:0": {"input": 0.00875, "output": 0.152},
    "amazon.nova-pro-v1:0": {"input": 1.68, "output": 1.92},
    "anthropic.claude-3-5-haiku-20241022-v1:0": {"input": 0.8, "output": 4.0},
    "anthropic.claude-3-5-sonnet-20241022-v2:0": {"input": 3.0, "output": 15.0},
    "anthropic.claude-3-haiku-20240307-v1:0": {"input": 0.25, "output": 1.25},
    "anthropic.claude-3-opus-20240229-v1:0": {"input": 15.0, "output": 75.0},
    "anthropic.claude-haiku-4-5-20251001-v1:0": {"input": 1.0, "output": 5.0},
    "anthropic.claude-opus-4-6-v1": {"input": 5.0, "output": 25.0},
    "anthropic.claude-opus-4-8": {"input": 5.0, "output": 25.0},
    "anthropic.claude-sonnet-4-6": {"input": 3.0, "output": 15.0},
    "anthropic.claude-sonnet-5": {"input": 3.0, "output": 15.0},
    "cohere.command-r-plus-v1:0": {"input": 3.0, "output": 15.0},
    "cohere.command-r-v1:0": {"input": 0.5, "output": 1.5},
    "meta.llama3-1-70b-instruct-v1:0": {"input": 0.72, "output": 0.72},
    "meta.llama3-1-8b-instruct-v1:0": {"input": 0.11, "output": 0.22},
    "mistral.mistral-large-2407-v1:0": {"input": 5.2, "output": 12.0},
}
